default_context:
    full_name: X Author Name
    email: x-pt@example.com
    github_username: x-pt
    project_name: Example Rs
    project_slug: example-rs
    package_name: example_rs
    project_desc: A nice example project
    project_version: 0.0.1
