default_context:
    full_name: X Author Name
    email: x-pt@example.com
    github_username: x-pt
    project_name: Example Cxx CMake
    project_slug: example-cxx-cmake
    package_name: example_cxx_cmake
    project_desc: A nice example project

    # C++
    cxx_build_tool: cmake
