default_context:
    full_name: X Author Name
    email: x-pt@example.com
    github_username: x-pt
    project_name: Example CUDA CMake
    project_slug: example-cuda-cmake
    package_name: example_cuda_cmake
    project_desc: A nice example project
    project_version: 0.0.1

    # C++
    cxx_build_tool: cmake
