name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:
{% raw  %}
jobs:
    build-and-test:

        name: ${{ matrix.toolchain }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                toolchain:
                    - linux-gcc
                    - windows-msvc

                configuration:
                    - Debug

                include:
                    -   toolchain: linux-gcc
                        os: ubuntu-latest
                        compiler: gcc

                    -   toolchain: windows-msvc
                        os: windows-latest
                        compiler: msvc

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3

            -   name: Configure (${{ matrix.configuration }})
                run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.configuration }}

            -   name: Build with ${{ matrix.compiler }}
                run: cmake --build build

            -   name: Test
                working-directory: build
                env:
                    CTEST_OUTPUT_ON_FAILURE: 1
                run: ctest -C ${{ matrix.configuration }}
{% endraw  %}
