default_context:
    full_name: X Author Name
    email: x-pt@example.com
    github_username: x-pt
    project_name: Example Py
    project_slug: example-py
    package_name: example_py
    project_desc: A nice example project

    # Python
    python_version: 3.11
